### ISSUE TITLE
Integrate Pontoon

### ISSUE THREAD

**Issue by ozten** [mozilla/betachannel#12]
We want to integrate Pontoon for localization

cc @mathjazz

**Comment by mathjazz** [comment]
Yay!

First, we need to pick the i18n library. If we use gettext, Pontoon will match extracted strings against HTML textnodes.

If we use webL10n, Pontoon will match make every HTML element with data-l10n-id attribute localizable, which is a more reliable method.

More:
https://developer.mozilla.org/en-US/docs/Implementing_Pontoon_Mozilla.
