### ISSUE TITLE
Some apps won't download

### ISSUE THREAD

**Issue by ozten** [mozilla/betachannel#39]
After installing http://d2gk.co/app/v/8/install/nick@mozilla.com,Calculator
Download fails:

```
E/GeckoConsole(  110): [JavaScript Error: "Permission denied for <app://system.gaiamobile.org> to create wrapper for object of class UnnamedClass" {file: "app://system.gaiamobile.org/js/app_install_manager.js" line: 390}]
I/Gecko   (  110): Event handler expection [Exception... "[JavaScript Error: "Permission denied for <app://system.gaiamobile.org> to create wrapper for object of class UnnamedClass" {file: "app://system.gaiamobile.org/js/app_install_manager.js" line: 390}]'[JavaScript Error: "Permission denied for <app://system.gaiamobile.org> to create wrapper for object of class UnnamedClass" {file: "app://system.gaiamobile.org/js/app_install_manager.js" line: 390}]' when calling method: [nsIDOMEventListener::handleEvent]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0"  data: yes]
```

**Comment by ozten** [comment]
```E/GeckoConsole(  341): Content JS ERROR at app://homescreen.gaiamobile.org/js/icon_retriever.js:67 in onerror: error  while HTTP GET:  app://{d161d284-d2ff-49b5-921b-2249b98fc2fe}/style/icons/icon_84.png

```
```

**Comment by ozten** [comment]
Looking at the package:

`file style/icons/icon_84.png
style/icons/icon_84.png: PNG image data, 84 x 84, 8-bit/color RGBA, non-interlaced`

**Comment by nickdesaulniers** [comment]
[app_install_manager.js 1.3](https://github.com/mozilla-b2g/gaia/blob/v1.3/apps/system/js/app_install_manager.js#L390)
[master](https://github.com/mozilla-b2g/gaia/blob/master/apps/system/js/app_install_manager.js#L390)

**Comment by ozten** [comment]
1.3.0.0-prerelease

```
E/GeckoConsole(  110): Content JS INFO at app://system.gaiamobile.org/js/app_install_manager.js:354 in ai_handleDownloadError: downloadError event, error code is WRONG_APP_STORE_ID
I/Gecko   (  110): RemoteOpenFileParent: file '/data/local/webapps/{9a3f1710-6492-4b88-9afe-b6f306303f8c}/application.zip' was not found!
I/Gecko   (  359): IPDL protocol error: [PRemoteOpenFileChild] Received an invalid file descriptor! 
E/GeckoConsole(  359): Content JS ERROR at app://homescreen.gaiamobile.org/gaia_build_defer_index.js:62 in onerror: error  while HTTP GET:  app://{9a3f1710-6492-4b88-9afe-b6f306303f8c}/style/icons/icon_84.png
```

**Comment by ozten** [comment]
I've found that having more than one app installed triggers `error code is WRONG_APP_STORE_ID`.

Removing all apps installed via betafox, then re-installing an app works.

**Comment by ozten** [comment]
These apps all have the same origin!

One app per origin, duh!

Subdomains?

**Comment by mykmelez** [comment]
Webapps.jsm says:

> ```
> // We're currently launching WRONG_APP_STORE_ID for all the mismatch kind of
> // errors, and APP_STORE_VERSION_ROLLBACK for the version error.
> ```
- http://mxr.mozilla.org/mozilla-central/source/dom/apps/src/Webapps.jsm?rev=31de1a84b27f#3448

Where the "app store ID" comes from the META-INF/ids.json file in the package, per http://mxr.mozilla.org/mozilla-central/source/dom/apps/src/Webapps.jsm?rev=31de1a84b27f#3414.

Is it possible that the packages are reusing an ID in META-INF/ids.json? That would definitely trigger WRONG_APP_STORE_ID (although it isn't the only way to trigger that error).

**Comment by ozten** [comment]
> Do you have access to the package?

On any of these pages, click the linked size, which goes to the package.zip.

http://d2gk.co/app/v/8/install/nick@mozilla.com,Calculator has [59309kb](http://d2gk.co/packaged/v/8/app/nick%40mozilla.com%2CCalculator/package.zip)

**Comment by ozten** [comment]
So `META-INF/ids.json` has

```
{
  "id": "test_app_identifier",
  "version": 1
}
```

I haven't done any work in ids.json since our prototype. Where can I find out all the requirements to enhance [sign_app.py](https://github.com/mozilla/betafox/blob/master/server/bin/sign_app.sh#L30) which uses [sign_b2g_app.py](https://github.com/mozilla/betafox/blob/master/server/bin/sign_b2g_app.py#L101)? Is there a spec or MDN doc that describes ids.json?

I'll munge the `manifest.name` into [a-z_] characters and pass through the string `manifest.version` into these fields (?).

**Comment by mykmelez** [comment]
I don't know of any such doc, although [bug 791741](https://bugzilla.mozilla.org/show_bug.cgi?id=791741) tracked the implementation of package signing, and [bug 814136](https://bugzilla.mozilla.org/show_bug.cgi?id=814136) contains useful info about what the implementation expects to find in ids.json.

**Comment by ozten** [comment]
It looks like `ids.json` usually contains:

```
{"version": 1541727, "id": "8bcde521-3e5b-4e0c-879d-26eccfa0b607"}
```

Probably `id` should be stable across versions. I don't have admin access to marketplace to confirm this.

`version` must be an integer.

Depends on Issue #46

**Comment by ozten** [comment]
This is fixed.
