### ISSUE TITLE
Log in JSON format

### ISSUE THREAD

**Issue by oremj** [mozilla/betachannel#54]
We should use something like winston or bunyan for JSON logging, so we can parse and ship the logs with heka.

**Comment by ozten** [comment]
Fixed in 38affcc87d2e91f1f5e4176a3082776630096d18.

Two new config options added:

```
logLevel = 'info';
logFile = './var/log/betafox.log';
```

Example log lines:

```
{"level":"info","message":"doing health check","timestamp":"2014-07-10T23:05:03.089Z"}
{"level":"error","message":"Created S3 Bucket","timestamp":"2014-07-10T23:05:03.894Z"}
```
